apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-database
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-database
subjects:
- kind: ServiceAccount
  name: keycloak-database
