apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: PROVISIONER_NAME
              value: nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: "ADD YOUR SERVER HERE"
            - name: NFS_PATH
              value: "ADD YOUR EXPORTED PATH HERE"
      volumes:
        - name: nfs-client-root
          nfs:
            server: "ADD YOUR SERVER HERE"
            path: "ADD YOUR EXPORTED PATH HERE"
