---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cloudkits.cloudkit.io
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  group: cloudkit.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
                minimum: 1
                maximum: 10
                default: 1
              image:
                type: string
                default: "quay.io/innabox/cloudkit:latest"
              storage:
                type: object
                properties:
                  size:
                    type: string
                    default: "1Gi"
                  storageClassName:
                    type: string
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "512Mi"
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
            required:
            - size
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              phase:
                type: string
                enum:
                - "Pending"
                - "Running"
                - "Failed"
              replicas:
                type: integer
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.size
        statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: cloudkits
    singular: cloudkit
    kind: CloudKit
    shortNames:
    - ck 