# These objects are only needed if you don't have AAP installed.
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  annotations:
    environment: development
  labels:
    app.kubernetes.io/managed-by: kustomize
    environment: development
  name: dev-cloudkit
  namespace: foobar
spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: true
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   annotations:
#     environment: development
#   labels:
#     app.kubernetes.io/managed-by: kustomize
#     environment: development
#   name: dev-ansible-automation-platform-operator
#   namespace: foobar
# spec: {}
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   annotations:
#     environment: development
#   labels:
#     app.kubernetes.io/managed-by: kustomize
#     environment: development
#   name: dev-ansible-automation-platform
#   namespace: foobar
# spec:
#   channel: stable-2.5-cluster-scoped
#   installPlanApproval: Automatic
#   name: ansible-automation-platform-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
